- name: check conditions
  hosts:  local
  connection: local
  vars:
    Number: 11
  tasks:
  - name: check number
    ansible.builtin.debug:
      msg: "given number {{ Number }} is greater than 10"
    when: Number  > 10        