- name: demo on error handler
  hosts:  local
  connection: local
  tasks:
  - name: check if user exist or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true
  - name: check the data
    ansible.builtin.debug:
      msg: "{{ user_output }}"
  - name: create user
    ansible.builtin.command: add roboshop
    when: user_output.rc != 0